### ISSUE TITLE
Roblox is totally down

### ISSUE THREAD

**Issue by Bicheng-guo** [Status-Plus/StatusPlus#388]
Incident Status
Service Disruption

Components
User, Player, Creator

Locations
Website, Mobile App, Xbox App, Games, Studio, Asset Delivery, Data Store, Game Join, Avatar

October 28, 2021 4:00PM PDT[Investigating] Many player experience are impacted.

stay tuned.

October 28, 2021 8:44PM PDT[Identified] We identify the root cause as internal system issue and work on the fix.

October 29, 2021 7:21AM PDT[Identified] We are actively working on recovery. Some users started to have limited access.

October 29, 2021 12:48PM PDT[Identified] The team continues active work on full site recovery.

**Comment by FxllenCode** [comment]
This is a legacy tool. Please continue using Status+ on Discord while I develop a new backend and website.
